version: 0.2
phases:
  install:
    commands:
      - sudo docker pull gcc
  build:
    commands:
      - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp gcc make
artifacts:
  files:
    - ./main